add more actions
toger5/matrix-rust-sdk pull request #7
Opened 2023-07-25 12:46 UTC by toger5

- [ ] Public API changes documented in changelogs (optional)

Signed-off-by:

2023-07-25 13:38 UTC, daniel-abramov requested changes

2023-07-25 13:38 UTC, daniel-abramov commented on crates/matrix-sdk/src/widget_api/messages/from_widget.rs
> +    GetSupportedApiVersion(MessageBody<(), SupportedVersions>),
It probably ought to be:

```rust
    #[serde(rename = "supported_api_versions")]
    GetSupportedApiVersion(MessageBody<(), ()>),
```

Because the message from the widget to request the supported API version has an empty body and it is not allowed to have the `response` field to be set to certain values containing versions, right? (i.e. it's the client that is supposed to reply with the versions, not the other way around).

2023-07-25 13:38 UTC, daniel-abramov commented on crates/matrix-sdk/src/widget_api/messages/from_widget.rs
> +    Navigate(MessageBody<String, Result<(), String>>),
Likewise, the navigate message **from** widget is probably supposed to only contain a URL (`String`) in it (in a request/data field, but no response field).

2023-07-25 13:38 UTC, daniel-abramov commented on crates/matrix-sdk/src/widget_api/messages/from_widget.rs
> +    GetOpenId(MessageBody<(), GetOpenIdResponse>),
Same for the OpenID request I suppose? 🙂

2023-07-25 13:38 UTC, daniel-abramov commented on crates/matrix-sdk/src/widget_api/messages/from_widget.rs
> +    ReadRelations(MessageBody<ReadEventRequest, ReadEventResponse>),
Same for these fields if I'm not mistaken? 🙂

2023-07-25 13:38 UTC, daniel-abramov commented on crates/matrix-sdk/src/widget_api/messages/from_widget.rs
> +}
We are missing the response parts here.

2023-07-25 13:38 UTC, daniel-abramov commented on crates/matrix-sdk/src/widget_api/messages/to_widget.rs
> +}
It generally looks good, but it has a problem similar to `FromWidgetMessage`, i.e. it lacks responses and it allows requests to have a response field set.

Should we probably replace `MessageBody<>` with separate `RequestBody` and `ResponseBody` if that's easier to understand? (I believe that was something that confused you 🙂)

2023-07-25 13:45 UTC, toger5 commented on crates/matrix-sdk/src/widget_api/messages/from_widget.rs
> +    GetSupportedApiVersion(MessageBody<(), SupportedVersions>),
It is still supposed to have that field. The widget will send a message that looks like this:
```json
"api":"fromWidget",
"action":"supported_api_versions",
"request_id":1,
"widget_id":2,
"data": {},
```
the client will respond with:
```
```json
"api":"fromWidget",
"action": "supported_api_versions",
"request_id":1,
"widget_id":2,
"data": {},
"response":["verions1", "version23"....,] 
```
So they both will be the same type (response is optional). The "api" field is not really a direction field but a prefix for the message type: message type = `$api+$action` But they always can be incoming and outgoing messages.

2023-07-25 13:49 UTC, toger5 commented on crates/matrix-sdk/src/widget_api/messages/to_widget.rs
> +}
I am still very much convinced, that this is the design we should want.
ToWidget and FromWidget are not defining the send direction they are just defining the type of messages and how they are supposed to be parsed.
The response is optional which makes it easy to differenciate if they are send as a response or as a request.

2023-07-27 12:58 UTC, daniel-abramov approved these changes

2023-07-27 12:58 UTC, daniel-abramov commented on crates/matrix-sdk/Cargo.toml
> +e2e-encryption = ["matrix-sdk-base/e2e-encryption", "matrix-sdk-base/message-ids", "matrix-sdk-sqlite?/crypto-store", "matrix-sdk-indexeddb?/e2e-encryption"]
Was it intentional to re-format it? :)

2023-07-27 13:21 UTC, daniel-abramov approved these changes

2023-07-27 13:22 UTC, merged